before_script:
  - docker info

build_image:
  script:
    - docker build -t python-time .

variables:
  DOCKER_HOST: tcp://localhost:2375/
  DOCKER_DRIVER: overlay2
  APP_NAME: python-time

deploy:
  stage: deploy
  image: alpine/helm:3.2.1
  script:
    - helm upgrade ${APP_NAME} ./python-time --install --namespace default
  rules:
    - if: $CI_COMMIT_BRANCH == 'master'
      when: always


